### ISSUE TITLE
Read-only access by email domain

### ISSUE THREAD

**Issue by tore-statsig** [statsig-io/statsig-feedback#11]
Is there a way to grant everyone on the same email domain automatic read-only access to a project? I think it makes sense to be intentional about who has edit permissions, but it would be nice to not have to individually invite all new team members to view gates.

**Comment by tore-statsig** [comment]
We've discussed internally and can work to support this feature in the next few weeks.

**Comment by marcos-statsig** [comment]
Forgot to comment here when this was deployed, this is available now to allow any teammates with the same email domain join a project automatically with any role. Documentation about this feature here: https://docs.statsig.com/console/accessManagement/overview
