### ISSUE TITLE
Better Slack updates

### ISSUE THREAD

**Issue by matthewtole** [statsig-io/statsig-feedback#14]
As the best way to know when changes have been made to feature gates, it would be really nice to have more details in the message.

So instead of saying just "Updated rules" it could say something like:

> Added new rule "Rule Name"
> Modified rule "Rule Name"
> Removed rule "Rule Name"

That could be a good first step, and then in the future it could give an explanation of the rule that was added.

**Comment by roim** [comment]
Thanks Matthew! This was on our backlog. Since your guys are using the Slack integration as your main notification channel, I'll bump priority and try to get some more descriptive updates this week.

**Comment by roim** [comment]
I coded the change you requested here and it'll be part of our next deployment. We also improved content in other changelog messages.

We'll keep improving the changelog over time, do let me know if you have more feedback on these updates!

**Comment by marcos-statsig** [comment]
Forgot to update here the changes Rodrigo mentioned have been deployed for a while. Closing the issue now, feel free to open another issue if there's any further concerns!
