### ISSUE TITLE
refine experience when accepting multiple project invites 

### ISSUE THREAD

**Issue by vmadhusudanan** [statsig-io/statsig-feedback#15]
Hitting "Accept" shouldn't redirect you to the project; visibly show that the invite has been acted on (remove or gray out), without requiring a refresh. 

![image](https://user-images.githubusercontent.com/31516123/126404659-1c5fe607-0e56-41f7-8bee-8dfd56473906.png)

More context at 
External https://statsigcommunity.slack.com/archives/C01QVL20EDD/p1626753671211500
Internal https://statsig.workplace.com/groups/343555053940634/permalink/357386859224120/

**Comment by marcos-statsig** [comment]
This experience has been optimized, we now open a dialog to allow users to accept multiple projects without being redirected.
