### ISSUE TITLE
Okta SSO Integration

### ISSUE THREAD

**Issue by jefftto** [statsig-io/statsig-feedback#16]
Is there Okta SSO support?

**Comment by tore-statsig** [comment]
Hey Jeff, thanks for the question!

We currently do not support Okta SSO, but @marcos-statsig was working on adding some initial email domain management on the Statsig side for auto-inviting new users to company projects.

We can work on integrating with Okta, can you give us an idea of how important this is for you?  If you have any additional requirements for such an integration, please update this issue with more information as well

**Comment by alex-statsig** [comment]
We opened the gate for Okta SSO yesterday. You can check out the setup documentation at https://docs.statsig.com/console/accessManagement/sso. Let us know if this is missing any needed features.
