### ISSUE TITLE
Updating feature gates sometimes freezes the page 

### ISSUE THREAD

**Issue by ksapchuk** [statsig-io/statsig-feedback#17]
Adding a rule with a custom field to a feature gate sometimes freezes https://console.statsig.com/.

Repro steps:
- Add a feature gate
- Add a rule with a custom field and an "Any of" operator
- Save

Expected: 
Feature gate is saved

Actual: 
Page is hanging

This happens on Chrome Version 92.0.4515.131 (Official Build) (arm64)

**Comment by tore-statsig** [comment]
Thanks for reporting this issue!  We will investigate immediately

**Comment by tore-statsig** [comment]
Confirmed I was able to repro, thanks for the repro steps!

**Comment by tore-statsig** [comment]
This appears to be a broader issue, not isolated to just custom fields

**Comment by tore-statsig** [comment]
Correction - if you are modifying a gate which already has a custom condition on it, then any of your changes when or after you add that custom field condition freeze the page on save

**Comment by tore-statsig** [comment]
This has been resolved.  Thanks again for the report!
