### ISSUE TITLE
Flutter/Dart SDK support

### ISSUE THREAD

**Issue by guillempuche** [statsig-io/statsig-feedback#18]
Flutter usage and community is growing. It's amazing how easily you can create native apps for Android, iOS and web (even desktop).

The community would use your SDK, we depend too much on Firebase services (because Google is behind Flutter, also for A/B testing).

**Comment by tore-statsig** [comment]
We hear you!  Flutter is next on our list of client SDKs.  We don't currently have it prioritized but I'll try to start prototyping it towards the end of February.  Would you be interested in taking it for a spin once it's ready?  We'd definitely appreciate the feedback

**Comment by guillempuche** [comment]
Fantastic news! Also you could think to make it compatible with Angular Dart.

I would love to try it to where I work (small ed-tech company).

**Comment by tore-statsig** [comment]
We did end up starting it back in February, but it ended up on the back burner since then.  We dont currently have plans to pick this pack up, but will update here when we do

**Comment by dan-loomb** [comment]
Hey All, just wanted to update here and say that work on the Flutter/Dart SDK is back underway. Basic functionality is complete and it is now mostly stability and edge case work to do. Hoping to have a release by the end of July. I will post back once v1 is released.

**Comment by tore-statsig** [comment]
@daniel-statsig published this today!

https://pub.dev/packages/statsig

https://docs.statsig.com/client/dartSDK

**Comment by guillempuche** [comment]
Can you consider decreasing the meta version package?

I consider we're using a quite upgraded Flutter `2.10.5` and Dart `>=2.16.0` but still dep `flutter_test` is incompatible.

Error when installing `statsig: ^0.3.0`:
```
Because every version of flutter_test from sdk depends on meta 1.7.0 and every version of statsig depends on meta ^1.8.0, flutter_test from sdk is incompatible with statsig.
So, because company_alpha depends on both statsig ^0.3.0 and flutter_test from sdk, version solving failed.
```

**Comment by dan-loomb** [comment]
@guillempuche, sorry about this, it has been an open issue for a couple days now. I just pushed 0.3.1 that addresses this. Let me know if you have any other questions. Cheers.

https://pub.dev/packages/statsig/versions/0.3.1
