### ISSUE TITLE
GetConfig for Android fails

### ISSUE THREAD

**Issue by Rolstenhouse** [statsig-io/statsig-feedback#19]
Statsig getConfig on Android fails when minification is enabled . 

Solution is to add `-keep class com.statsig.**{*;}` to the proguard-rules.pro file

**Comment by vijaye-statsig** [comment]
That's strange.  @tore-statsig to investigate progaurd side effects

**Comment by tore-statsig** [comment]
This is a great catch - and actually not so strange.  DynamicConfig is our helper class for developers to integrate with DynamicConfigs and Experiments set up in the Statsig console, but it is actually an unused class in the SDK itself.  So proguard took the liberty of stripping it out.

Thanks for the report, we will publish a fixed version shortly

**Comment by tore-statsig** [comment]
Fix published in v4.2.4

https://github.com/statsig-io/android-sdk/releases/tag/v4.2.4
