### ISSUE TITLE
Feature gate's pass rate 

### ISSUE THREAD

**Issue by youminkim** [statsig-io/statsig-feedback#2]
In Feature Gate, I made simple rollout setting with 50% pass rate
![Screenshot 2021-06-10 at 12 16 05 AM](https://user-images.githubusercontent.com/317132/121391957-84265180-c981-11eb-8976-e4b57e7943b0.png)

In Pulse, however, I got pass 98% rate
![Screenshot 2021-06-10 at 12 17 50 AM](https://user-images.githubusercontent.com/317132/121392119-a91ac480-c981-11eb-8556-e2bb572f2909.png)

This is not supposed to be 50% pass rate? Based on my manual checking in my website, the feature gate pass rate is around 50%

**Comment by marcos-statsig** [comment]
Hey Youmin, thanks for flagging this! We've identified the issue as being related to how we were rendering the results and have fixed this. We'll be rolling out the fix in a few hours, and your data will be displayed correctly.

**Comment by youminkim** [comment]
Thank you! Seems working fine now

**Comment by marcos-statsig** [comment]
Great, thank you again for flagging this!
