### ISSUE TITLE
On page refresh, some part of dark mode CSS is not retained. 

### ISSUE THREAD

**Issue by shivamsingh19** [statsig-io/statsig-feedback#20]
On page refresh, some part of dark mode CSS is not retained. Need to login again to reflect changes.

Before page refresh.
![image](https://user-images.githubusercontent.com/12456991/151794919-8d83eb8b-9f1b-4161-bd05-6ff2163104e6.png)

After page refresh.
![image](https://user-images.githubusercontent.com/12456991/151795201-61117608-414a-458d-88f0-ebd7296be74a.png)

**Comment by tore-statsig** [comment]
Thanks for the report!  We are aware of this but were not able to repro in the past, we will try your repro steps

**Comment by alex-statsig** [comment]
Hey @shivamsingh19, thanks for the detailed report. I think we had trouble reproing locally, but your production repro worked and helped us find the issue. It should be resolved now!
