### ISSUE TITLE
Ultrasound Card in the Doc's Overview Page 404

### ISSUE THREAD

**Issue by andy-statsig** [statsig-io/statsig-feedback#22]
![Screen Shot 2022-06-30 at 10 19 39 AM](https://user-images.githubusercontent.com/108023879/176738847-07a60bf6-f1ec-4685-bee3-4b8b9805a506.png)

The link to this card is https://docs.statsig.com/console/ultrasound, but should be https://docs.statsig.com/ultrasound.

**Comment by jasonwzm** [comment]
Fixed by https://github.com/statsig-io/docs/pull/311
