### ISSUE TITLE
`api.statsig.com/v1` blocked by default ublock origin adblocker (JS Client)

### ISSUE THREAD

**Issue by smblee** [statsig-io/statsig-feedback#24]
The default configuration for one of the most popular adblocker ublock origin seems to block out the `api.statsig.com` domain. After digging in, one of the default list that gets pulled in is [easyprivacy](https://easylist.to/#easyprivacy), which includes `statsig.com` as part of the domain. (refer to documentation here: https://github.com/gorhill/uBlock)

I think theres two potential problems here - one is API call to `initialize` doesnt work (not sure what the implication there is), and there seems to be an infinite retry logic to try to `initialize` by the `statsig-js` client.

<img width="223" alt="image" src="https://user-images.githubusercontent.com/9781750/178118582-9efdce0a-8070-4aa9-902f-c5b617a11a4b.png">

**Comment by vijaye-statsig** [comment]
Thank you. We are aware of it and are appealing to unblock it with easy list.

**Comment by smblee** [comment]
Not being able to hit `initialize` API seems to break the experience for users - We can resort to SSR + hydration to CSR client with `localMode = true` enabled to essentially only rely on the initial hydration for now.

**Comment by tore-statsig** [comment]
In addition, we've separated initialization and event logging in newer SDK versions.  I'd recommend checking out the newest 

js client sdk: https://github.com/statsig-io/js-client/releases/tag/v4.17.0

or react sdk: https://github.com/statsig-io/react-sdk/releases/tag/v1.13.0

**Comment by tore-statsig** [comment]
With all of these efforts combined, this issue is closed
