### ISSUE TITLE
Feature flag value false after the refresh v1/rgstr api call

### ISSUE THREAD

**Issue by mhshry** [statsig-io/statsig-feedback#26]
getting feature gate value false after the refresh the page & call the rgstr api.

sdkType: "js-client"
sdkVersion: "4.18.0"

gate: "test_feature_gate"
gateValue: "false"
reason: "Unrecognized"
ruleID: ""
time: 1659002674066
secondaryExposures: []

**Comment by tore-statsig** [comment]
"Unrecognized" indicates that the flag you are trying to check does not exist.  Are you waiting for initialization to complete before checking flags?

Also, if you can provide a companyID or additional information, we can investigate more

**Comment by mhshry** [comment]
Thanks, Issue resolved
