### ISSUE TITLE
Invites don't honor the invited role

### ISSUE THREAD

**Issue by nevir** [statsig-io/statsig-feedback#28]
When I invite new members to my project (as admin), they end up joining as regular Members

Note that I do have auto-add (as Member) for my domain enabled

**Comment by tvh-statsig** [comment]
Hey @nevir - thanks for the report! We were able to track down the issue and should have this fixed sometime this week

**Comment by nevir** [comment]
Nice!

**Comment by tvh-statsig** [comment]
The fix for this should have gone up around August 25th - feel free to ping if you run into any other issues around this!
