### ISSUE TITLE
Feature Gate/Dynamic Config change review process

### ISSUE THREAD

**Issue by sgianelli** [statsig-io/statsig-feedback#3]
One feature that I think would be really great to have is the ability to submit a change for review from your other teammates before it takes effect. This would help to mitigate risk around accidental feature targeting changes or incorrect configurations on dynamic configs.

**Comment by gblee0410** [comment]
Hi, I'm GB who is a Product Designer on Statsig. Thanks for using our product and providing this valuable feedback 👍 

I'm here to give an update on this issue -- **we've finalized the designs and our engineers will start working on it this week.** Here are some of the things you can expect (for all the new updates, I've included some screenshots that illustrates our approach):

- We'll be adding a project-level setting where the admin can set if all the feature gate changes need review or not
- For projects that enabled the mandatory review setting, feature gate changes will require submission of the reviewers (from the same project) and a short description of the changes made
- There will be a "Preview State" view where the person who requested the change can make additional changes or to cancel the submission. For others, they can either approve or reject. _(**Note:** we are opening up the ability to approve by anyone in the project, not just the people who were defined to be reviewers_ 
- On feature gates that is pending review, we will be highlighting at the very top with description & reviewer information as well as the link to the "Preview State" to view the changes requested
- We will be introducing a new page called "Review" where you can view all your current & past feature gate reviews. Upon getting requests to be a reviewer, we will trigger a notification and send you an email
- Lastly, in the feature gate tab view, anyone in the same project will be able to see feature gates that have pending reviews from the tag

![Screen Shot 2021-06-14 at 2 12 13 PM](https://user-images.githubusercontent.com/82126616/121960357-d87f5780-cd1a-11eb-9604-7358ca5af379.png)
![Screen Shot 2021-06-14 at 2 12 24 PM](https://user-images.githubusercontent.com/82126616/121960363-da491b00-cd1a-11eb-8d29-6ff7c699eafe.png)
![Screen Shot 2021-06-14 at 2 12 39 PM](https://user-images.githubusercontent.com/82126616/121960367-dae1b180-cd1a-11eb-979f-bd99e809e8ce.png)
![Screen Shot 2021-06-14 at 2 13 07 PM](https://user-images.githubusercontent.com/82126616/121960372-db7a4800-cd1a-11eb-8b56-1ef885d34cb2.png)
![Screen Shot 2021-06-14 at 2 31 50 PM](https://user-images.githubusercontent.com/82126616/121962206-47f64680-cd1d-11eb-8c5a-d68362e4065d.png)

**Comment by sroyal-statsig** [comment]
Thanks again for the request! Starting today you can require review for all gate and config changes by navigating to the project settings page. I'm closing this issue for now but feel free to request additional functionality in a new issue.
![Screen Shot 2021-06-22 at 5 33 10 PM](https://user-images.githubusercontent.com/76536058/123016744-1ebe6180-d380-11eb-9a4f-33344bffa4be.png)
