### ISSUE TITLE
APIs for listing, patching and deleting overrides for feature gates

### ISSUE THREAD

**Issue by stormy-petrel** [statsig-io/statsig-feedback#30]
To provide self-serving client debugging, we need APIs/ SDK methods to patch, and delete the IDs of a [feature gate's overrides](https://docs.statsig.com/console-api/gates).  We also need to retrieve the overrides of all feature gates 

- `PATCH  /gates/{gate_id}/overrides/{id}?list_type=[pass,fail]`
- `DELETE  /gates/{gate_id}/overrides/{id}?list_type=[pass,fail]`
- `GET /gates/overrides/{id}`  Retrieve the overrides status of all feature gates for a given ID.   Return false or true for each feature gate.

The two recommendations in [Statsig unit testing](https://docs.statsig.com/guides/testing#unit-tests) don't satisfy the same requirement here: 

-  [Override methods](https://docs.statsig.com/client/jsClientSDK#how-can-i-mock-the-sdkoverride-gates-in-tests)  are corresponding to [existing APIs](https://docs.statsig.com/console-api/gates). They are inefficient for App clients.
-  [Segment](https://docs.statsig.com/console-api/segments) can be an alternative.  However, Segment is better to serve as the 2nd-level override for all feature gates.  Like enabling company wide dog-fooding, so that an important feature can be enabled automatically for all employees to test and fire bugs before general public rollout with  experiments.  Feature Gate's override should take precedence over the segments attached.   Also, to support engineers/testers self-serving through app/client,  the feature gate override is the most efficient and scalable solution.

**Comment by vijaye-statsig** [comment]
@jacob-statsig

**Comment by tore-statsig** [comment]
Thanks for the request. We did implement overrides via the console API for experiments, and can extend that to support feature gates as well.

**Comment by jacob-statsig** [comment]
We have addressed the first two bullet points (see docs here: https://docs.statsig.com/console-api/gates).
