### ISSUE TITLE
Experiments tab not loading

### ISSUE THREAD

**Issue by phillee** [statsig-io/statsig-feedback#34]
Cannot open experiments. Either hangs when clicking on the tab or loads a blank page

**Comment by tvh-statsig** [comment]
Hey @phillee - we're not seeing errors thrown for you in our logging, so I wonder if this might be some transient network issues? If you're able to repro this consistently, could you attach a screen recording of it happening? The behavior we see might help us narrow things down. Thanks!

**Comment by phillee** [comment]
Cleared my cache and works again now. Thanks!
