### ISSUE TITLE
Python client sdk

### ISSUE THREAD

**Issue by ankurcha** [statsig-io/statsig-feedback#36]
Python client side sdk for putting into cli applications and such would be great

**Comment by tore-statsig** [comment]
If you wanted to, you could use this SDK for that.  You'd just have to do a few things manually:

1) decide when to initialize, or ship the config spec with the package and use the data adapter to initialize from that.

2) manually flush() events - the background thread to flush events likely wont run

The only other thing is that it would not get updated values - typically background threads we rely on to flush and sync with statsig servers dont run from a cli, so you'd need to determine that.  But you probably want the values to be static for a certain period of the session anyway.

**Comment by tore-statsig** [comment]
Going to close this for now, we have no plans to implement a separate package so the suggested workarounds are the best path forward
