### ISSUE TITLE
Commenting Out Array Elements in ParameterStore Permanently Removes Them

### ISSUE THREAD

**Issue by OrcunJoyoLabs** [statsig-io/statsig-feedback#50]
### Issue

When working with array values in ParameterStore, commenting out an element (for temporary testing purposes) causes that element to be permanently removed from the array upon saving. This makes it difficult to perform quick experimental changes since commented elements cannot be easily uncommented later.

Given an array value in ParameterStore, e.g.: 

```
{
  "features": [
    "feature1",
    "feature2",
    "feature3"
  ]
}
```
Commenting out an element and saving, you'll see at the next re-open in the UI that the element is gone. Making it difficult to revert the change.

**Expected Behavior**

Commented elements should either:

- Be preserved in the source but ignored during runtime evaluation, OR
- Show a warning before saving that commented elements will be permanently removed
- Or commenting out should not be given as an option

**Comment by tore-statsig** [comment]
I dont see the issue here?  If you remove and item from the array, it is gone.  If you want to target your changes only to a non production environment, you should be able to do that with non static values for a parameter store

**Comment by tore-statsig** [comment]
Oh I think I misunderstood - you are saying in the console UI, that when you comment out and save and then reopen, the commented out line doesnt exist any more.

For the moment, I dont think we will invest in fixing this, so Im going to close this out.  I can see how it would be a nice addition in the future
