### ISSUE TITLE
[Bug][Dart SDK] Parameter Store API doesn't work when variable linked with Dynamic Config

### ISSUE THREAD

**Issue by OrcunJoyoLabs** [statsig-io/statsig-feedback#52]
**Description**
The Parameter Store is not properly reading values from Dynamic Configs in the Dart SDK. When attempting to retrieve a parameter value that references a Dynamic Config, the Parameter Store returns null instead of the expected value.

**Environment**

SDK: Statsig Dart SDK 1.2.2
Platform: Dart

**Steps to Reproduce**

- Create a Dynamic Config named "my_test_dynamic_config"
- Set the Dynamic Config value to:

```json
    {"my_test_param": "test value"}
```

- Create a Parameter Store named "my_test_param_store"
- Create a parameter named "my_test_param" of type string
- Change my_test_param's reference type to Dynamic Config
- Select "my_test_dynamic_config" and "my_test_param" as the reference path

Run the following code (after initializing Statsig):
```dart
final store = Statsig.getParameterStore("my_test_param_store");
print('Test param value: ${store.get("my_test_param")}');
```

**Expected Behavior**
The code should print: ```Test param value: test value```

**Actual Behavior**
The code prints: ```Test param value: null```

**Additional **Context****

- The same configuration works correctly when using the JavaScript SDK
- **Same dart code above runs fine if we use Static Values instead of Dynamic Config**
- The Dynamic Config appears to be properly set up as verified through the Statsig console
- The Parameter Store and parameter references are configured correctly as evidenced by working behavior in JS SDK

**Comment by tore-statsig** [comment]
Interesting, I just wrote a test case to try to reproduce this issue on the latest sdk (v1.2.2) but I was not able to reproduce

**Comment by tore-statsig** [comment]
My mistake - I think I have a repro now

**Comment by tore-statsig** [comment]
Should be fixed in https://github.com/statsig-io/dart-sdk/releases/tag/v1.2.3 - thanks for the report and sorry for the trouble

**Comment by OrcunJoyoLabs** [comment]
Now it works! Thank you!
