### ISSUE TITLE
"Test Gate" console does not refresh after saving gate changes

### ISSUE THREAD

**Issue by tore-statsig** [statsig-io/statsig-feedback#9]
"When you edit a gate, even after clicking save, the “test gate” console does not refresh and may show stale/incorrect data. Refreshing the page (or editing the contents of the test gate input) is required to update the data. Until I realized this, I spent a minute trying to debug how I’d set up my gate incorrectly, thinking the problem was with the new rules I’d written."

**Comment by tore-statsig** [comment]
We've reproduced the issue and we are working on address this.  Either we will disable the console for staged changes, or allow staged changes to evaluate using the console.  We estimate this will be fixed in the next week

**Comment by jhurwitz** [comment]
To clarify: I was unsurprised that the console didn't work for staged changes. The bigger bug is that, even after saving changes (at which point they are no longer staged), it still does not update to reflect the latest rules.

**Comment by alex-statsig** [comment]
@jhurwitz This should be fixed now, along with a change to make the tool explain why the given user passes/fails as well. Hope this is helpful!
